extends Node
## Task 11.1 — comprehensive test of every problem in ProblemLibrary.ALL.
## Runs each item through the live MathEngine session, verifies it returned a
## non-error, non-empty result (plots are checked for ≥10 finite samples),
## writes a Markdown report, and quits.

const REPORT_PATH := "i:/mathdot/task11_test_report.md"

var _items: Array = []        # flat: each entry = {cat, label, input, cmd, kind}
var _id_to_idx: Dictionary = {}
var _results: Array = []      # parallel: each = {ok, output, ms}
var _completed: int = 0
var _started_ms: int = 0
var _start_times: Dictionary = {}


func _ready() -> void:
	for cat_idx in range(ProblemLibrary.ALL.size()):
		var cat: Dictionary = ProblemLibrary.ALL[cat_idx]
		for it_idx in range(cat["items"].size()):
			var it: Dictionary = cat["items"][it_idx]
			_items.append({
				"cat": cat["name"],
				"label": it["label"],
				"input": it["input"],
				"cmd": it["cmd"],
				"kind": it.get("kind", "raw"),
			})
			_results.append(null)

	MathEngine.result_ready.connect(_on_result)
	# Wait for engine boot, then dispatch everything in order.
	await get_tree().create_timer(1.5).timeout
	_started_ms = Time.get_ticks_msec()
	for i in range(_items.size()):
		var item: Dictionary = _items[i]
		var cmd_to_send: String
		if item["kind"] == "plot":
			# Same sampling command the app uses for plotting.
			var n := 200
			var x_min := -10.0
			var x_max := 10.0
			var step := (x_max - x_min) / float(n)
			var params := MathFormatter.free_params(item["input"])
			var psub := ""
			for p in params:
				psub += ", %s=1.0" % p
			cmd_to_send = "on rounded; for i:=0:%d collect sub(x=(%f)+(i+0.5)*(%f)%s, %s); off rounded" % [
				n, x_min, step, psub, item["input"]]
		else:
			cmd_to_send = item["cmd"]
		var id := MathEngine.evaluate(cmd_to_send)
		_id_to_idx[id] = i
		_start_times[id] = Time.get_ticks_msec()


func _on_result(id: int, output: String, is_error: bool) -> void:
	if id < 0:
		return
	if not _id_to_idx.has(id):
		return
	var i: int = _id_to_idx[id]
	var item: Dictionary = _items[i]
	var ok := not is_error and output.length() > 0
	if item["kind"] == "plot":
		var ys := MathFormatter.parse_number_list(output)
		var finite_count := 0
		for v in ys:
			if is_finite(v):
				finite_count += 1
		ok = finite_count >= 10
	_results[i] = {
		"ok": ok,
		"output": output,
		"ms": Time.get_ticks_msec() - int(_start_times.get(id, _started_ms)),
	}
	_completed += 1
	if _completed == _items.size():
		_write_report()
		get_tree().quit()


func _write_report() -> void:
	var lines := PackedStringArray()
	var pass_n := 0
	var fail_n := 0
	var by_cat: Dictionary = {}
	var total_ms := 0
	for i in range(_items.size()):
		var item: Dictionary = _items[i]
		var r: Dictionary = _results[i]
		if r["ok"]:
			pass_n += 1
		else:
			fail_n += 1
		total_ms += int(r["ms"])
		var cat: String = item["cat"]
		if not by_cat.has(cat):
			by_cat[cat] = []
		by_cat[cat].append({
			"label": item["label"], "ok": r["ok"],
			"output": r["output"], "ms": r["ms"], "cmd": item["cmd"],
			"kind": item["kind"],
		})
	lines.append("# Task 11.1 — Comprehensive Menu-Library Test Report")
	lines.append("")
	lines.append("Auto-generated by `app/scripts/_libtest.gd` running against the live")
	lines.append("bundled engine. Every problem in `ProblemLibrary.ALL` was evaluated")
	lines.append("once; \"plot\" items were exercised via the same sampling command the")
	lines.append("app uses (200 samples over x ∈ [-10, 10]) and pass when ≥10 finite")
	lines.append("samples are returned.")
	lines.append("")
	lines.append("## Summary")
	lines.append("")
	lines.append("**%d passed / %d failed** out of %d total — wall time %.1f s." % [
		pass_n, fail_n, _items.size(), total_ms / 1000.0])
	lines.append("")
	var cat_order := ["Algebra", "Calculus", "Equations", "ODEs", "Matrices",
		"Series", "Trig", "Numbers", "Plots"]
	for cat in cat_order:
		if not by_cat.has(cat):
			continue
		var entries: Array = by_cat[cat]
		var cat_pass := 0
		for e in entries:
			if e["ok"]:
				cat_pass += 1
		lines.append("## %s — %d/%d" % [cat, cat_pass, entries.size()])
		lines.append("")
		lines.append("| ✓ | Problem | ms | Engine reply (truncated) |")
		lines.append("|---|---------|----|---------------------------|")
		for e in entries:
			var mark := "✅" if e["ok"] else "❌"
			var out: String = e["output"].replace("\n", " ").replace("|", "\\|")
			if out.length() > 90:
				out = out.substr(0, 87) + "…"
			lines.append("| %s | %s | %d | `%s` |" % [mark, e["label"], int(e["ms"]), out])
		lines.append("")
	if fail_n > 0:
		lines.append("## Failures (full output)")
		lines.append("")
		for cat in cat_order:
			if not by_cat.has(cat):
				continue
			for e in by_cat[cat]:
				if not e["ok"]:
					lines.append("### %s — %s" % [cat, e["label"]])
					lines.append("")
					lines.append("- cmd: `%s`" % e["cmd"])
					lines.append("- output:")
					lines.append("```")
					lines.append(e["output"])
					lines.append("```")
					lines.append("")
	var f := FileAccess.open(REPORT_PATH, FileAccess.WRITE)
	if f:
		f.store_string("\n".join(lines))
		f.close()
	print("REPORT_DONE pass=%d fail=%d total=%d ms=%d" % [
		pass_n, fail_n, _items.size(), total_ms])
